//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKHP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKy
    {
        public int MaSV { get; set; }
        public int MaHP { get; set; }
        public int NamHoc { get; set; }
    
        public virtual LopHocPhan LopHocPhan { get; set; }
        public virtual SinhVien SinhVien { get; set; }
        public virtual KetQuaHocTap KetQuaHocTap { get; set; }
    }
}
