//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKHP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        public int MaGV { get; set; }
        public int MaHP { get; set; }
        public int NamHoc { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual LopHocPhan LopHocPhan { get; set; }
    }
}
