//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKHP
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaHocTap
    {
        public int MaSV { get; set; }
        public int MaHP { get; set; }
        public int NamHoc { get; set; }
        public decimal DiemKT { get; set; }
        public decimal DiemGK { get; set; }
        public decimal DiemCK { get; set; }
        public Nullable<decimal> DiemTB { get; set; }
    
        public virtual DangKy DangKy { get; set; }
    }
}
