//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKHP
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHocPhan()
        {
            this.DangKies = new HashSet<DangKy>();
            this.Days = new HashSet<Day>();
        }
    
        public int MaHP { get; set; }
        public string TenHP { get; set; }
        public int SoTinChi { get; set; }
        public int SoTiet { get; set; }
        public int SoSVToiDa { get; set; }
        public int SoSVHienTai { get; set; }
        public int MaMH { get; set; }
        public string HocKy { get; set; }
        public int NamHoc { get; set; }
        public int ThoiKhoaBieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKy> DangKies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Day> Days { get; set; }
        public virtual ThoiKhoaBieu ThoiKhoaBieu1 { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
